version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout
      
      - setup_remote_docker:
        docker_layer_caching: true

      - run: make docker_build